/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify.
// It will be overwritten when you run "amplify push".

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:mock-pool-id",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_mockpool",
    "aws_user_pools_web_client_id": "mockclientid",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_social_providers": [],
    "aws_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "amantes-storage-mock",
    "aws_user_files_s3_bucket_region": "us-east-1",
    // Configuração da API (REST)
    "aws_cloud_logic_custom": [
        {
            "name": "AmantesAPI",
            "endpoint": "https://mock-api.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ]
};

export default awsmobile;